### ISSUE TITLE
Replace bash with Python

### ISSUE THREAD

**Issue by doctrino** [cognitedata/deploy-functions-oidc#48]
I don't think I am alone in that complicated bash scripts are hard to read, so I suggest replacing the bash script for finding changed functions with Python. Note GitHub Actions comes with Python 3.10 preinstalled, so there is no performance hit on this. 

I have already written such a script for a project [here](https://github.com/cognitedata/tech-demo-powerops/blob/main/build_scripts/changed_functions.py) and I am happy to add it here. 

@haakonvt Are you controlling this repo? wdyt?

**Comment by haakonvt** [comment]
Technically this repo is the responsibility of the Functions team, however, they don't touch it (even when someone breaks, no, yes, no, well yes 😂 ).

I'd love to see such changes @doctrino 👌

**Comment by doctrino** [comment]
Great, I will make a PR for it then. Already battle tested the script above and, hopefully, removed the bugs from it.
